Repository Andi-IM/desktop-project, pull requests merged in 2021-03, with the labels that each got.

#11 Adding Class Andi
  Andi.java
Labels: enhancement

#16 Merging request to Main
  Hakkan.java
  Minum.java
  Mulai.java
Labels: enhancement

#17 Revert "Merging request to Main"
  Hakkan.java
  Minum.java
  Mulai.java
Labels: bug, enhancement

#21 Pull request from hakkan-branch
  .github/settings.yml
  .github/workflows/inspector.yml
  Andi.java
  GetItem.java
  Hakkan.java
  Minum.java
  Mulai.java
Labels: feature
